[package]
name = "shashmap"
version = "0.1.0"
edition = "2021"

[dependencies]
shashmap-core = { path = "../shashmap-core", version = "0.1" }
hashbrown = { version = "0.14" }
parking_lot = "0.12"
lock_api = "0.4"
